server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:exploredb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: h2

axon:
  amqp:
    exchange: order.events
  eventhandling:
    processors:
      amqpEvents:
        source: complaintEventsMethod